server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    allow-circular-references: true
  application:
    name: technical-challenge
  profiles:
    active: local
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/technical_challenge
    username: postgres
    password: 415782
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}