version: '3.1'

services:
  db:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 415782
      POSTGRES_DB: technical_challenge
    volumes:
      - technical_challenge:/var/lib/postgresql

volumes:
  technical_challenge:
